const eventDetails = {
    hackathon: {
        title: "Hackathon TechWorld", category: "Programação", date: "20 Set 2026", time: "09:00 às 20:00", location: "Hub TechWorld · São Paulo, SP", company: "TechWorld Labs", state: "Próximo evento", image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1500&q=85",
        description: "Um dia de criação, troca e tecnologia. No Hackathon TechWorld, equipes irão desenvolver soluções para desafios reais, com mentorias, oficinas e uma apresentação final para especialistas do mercado.",
        schedule: [{ time:"09:00", title:"Credenciamento e café de boas-vindas", text:"Retire sua credencial e conheça o espaço do evento.", tag:"Recepção" },{ time:"09:45", title:"Abertura e apresentação dos desafios", text:"Conheça as regras, os mentores e os temas que serão trabalhados.", tag:"Palco principal" },{ time:"10:30", title:"Início do hackathon", text:"Forme seu time e comece a desenvolver sua solução.", tag:"Competição" },{ time:"14:00", title:"Mentorias com especialistas", text:"Tire dúvidas técnicas, de produto e de apresentação.", tag:"Mentoria" },{ time:"18:00", title:"Apresentação dos projetos", text:"Cada equipe terá cinco minutos para apresentar sua solução.", tag:"Pitch final" },{ time:"19:15", title:"Resultado e encerramento", text:"Divulgação dos vencedores e networking final.", tag:"Premiação" }],
        tournament: { status:"Em breve", rows:[{name:"Code Crafters",detail:"—",points:"0"},{name:"Byte Builders",detail:"—",points:"0"},{name:"Dev Horizon",detail:"—",points:"0"},{name:"Pixel Pioneers",detail:"—",points:"0"}] }
    },
    aiSummit: { title:"AI Summit 2026", category:"Inteligência Artificial", date:"28 Set 2026", time:"14:00 às 19:30", location:"Evento online", company:"Future AI", state:"Próximo evento", image:"https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1500&q=85", description:"Uma tarde de palestras e conversas sobre inteligência artificial, produtos e o futuro do trabalho. A transmissão será realizada pela plataforma TechWorld.", schedule:[{time:"14:00",title:"Abertura",text:"Boas-vindas e visão geral do encontro.",tag:"Ao vivo"},{time:"14:30",title:"IA aplicada a produtos",text:"Cases práticos de empresas brasileiras.",tag:"Palestra"},{time:"16:00",title:"Painel: ética e impacto",text:"Especialistas discutem os desafios da adoção de IA.",tag:"Painel"},{time:"18:00",title:"Networking virtual",text:"Conecte-se com outros participantes em salas temáticas.",tag:"Comunidade"}] },
    indieGame: { title:"Indie Game Night", category:"Games", date:"03 Out 2026", time:"18:30 às 22:00", location:"Arena GameForge · Rio de Janeiro, RJ", company:"GameForge", state:"Próximo evento", image:"https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1500&q=85", description:"Uma noite para jogar, descobrir títulos independentes e encontrar criadores. A programação reúne demonstrações, conversas e um torneio aberto para participantes.", schedule:[{time:"18:30",title:"Abertura da arena",text:"Credenciamento e acesso às estações de jogo.",tag:"Recepção"},{time:"19:00",title:"Mostra de jogos independentes",text:"Conheça os projetos selecionados da noite.",tag:"Exposição"},{time:"20:00",title:"Torneio Pixel Clash",text:"Disputas eliminatórias entre os inscritos.",tag:"Torneio"},{time:"21:30",title:"Premiação e encerramento",text:"Anúncio do campeão e networking.",tag:"Premiação"}], tournament:{status:"Inscrições abertas",rows:[{name:"Ana Martins",detail:"1º lugar provisório",points:"980"},{name:"Gustavo Silva",detail:"2º lugar provisório",points:"860"},{name:"Lucas Nunes",detail:"3º lugar provisório",points:"790"},{name:"Marina Costa",detail:"4º lugar provisório",points:"710"}] } },
    frontendWeek: { title:"Frontend Week", category:"Tecnologia", date:"12 Ago 2026", time:"09:00 às 18:00", location:"Evento online", company:"WebLab", state:"Evento realizado", image:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1500&q=85", description:"Uma imersão online em interfaces modernas, acessibilidade e boas práticas de desenvolvimento front-end. Este evento já foi concluído.", schedule:[{time:"09:00",title:"Boas-vindas",text:"Abertura da edição e apresentação dos convidados.",tag:"Realizado"},{time:"10:00",title:"Interfaces que conectam",text:"Palestra sobre experiência de usuário.",tag:"Realizado"},{time:"14:00",title:"Laboratório de acessibilidade",text:"Oficina prática com especialistas.",tag:"Realizado"},{time:"17:00",title:"Encerramento",text:"Resumo da edição e próximos passos.",tag:"Realizado"}] },
    startupConnection: { title:"Startup Connection", category:"Startups", date:"26 Jul 2026", time:"13:00 às 19:00", location:"Centro de Inovação · São Paulo, SP", company:"Launch Hub", state:"Evento realizado", image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1500&q=85", description:"Encontro entre empreendedores, investidores e pessoas interessadas em inovação. A edição reuniu painéis, mentorias e uma competição de pitches.", schedule:[{time:"13:00",title:"Credenciamento",text:"Recepção dos participantes.",tag:"Realizado"},{time:"14:00",title:"Painel de investidores",text:"Tendências para startups em estágio inicial.",tag:"Realizado"},{time:"16:00",title:"Pitch battle",text:"Apresentações das startups finalistas.",tag:"Torneio"},{time:"18:30",title:"Resultado e networking",text:"Premiação e encerramento.",tag:"Realizado"}], tournament:{status:"Resultado final",rows:[{name:"Nova Loop",detail:"Campeã",points:"96"},{name:"Solarise",detail:"2º lugar",points:"91"},{name:"Rota Verde",detail:"3º lugar",points:"88"},{name:"UpCare",detail:"4º lugar",points:"82"}] } }
};

const params = new URLSearchParams(window.location.search);
const event = eventDetails[params.get("id")] || eventDetails.hackathon;
const isUpcoming = event.state === "Próximo evento";

document.title = `${event.title} - TechWorld`;
document.getElementById("eventHero").innerHTML = `<img class="hero-image" src="${event.image}" alt="${event.title}"><span class="event-state ${isUpcoming ? "upcoming" : ""}">${event.state.toUpperCase()}</span><div class="hero-content"><span class="eyebrow">${event.category}</span><h1>${event.title}</h1><p>${event.company}</p><div class="hero-meta"><span><b>◷</b>${event.date} · ${event.time}</span><span><b>⌖</b>${event.location}</span></div></div>`;
document.getElementById("eventDescription").textContent = event.description;
document.getElementById("scheduleDate").textContent = event.date;
document.getElementById("scheduleList").innerHTML = event.schedule.map(item => `<article class="schedule-item"><div class="schedule-time">${item.time}</div><div class="schedule-info"><h3>${item.title}</h3><p>${item.text}</p><span class="schedule-tag">${item.tag}</span></div></article>`).join("");
document.getElementById("sideInfo").innerHTML = `<section class="info-card"><h3>Informações</h3><div class="info-list"><div><span>Organização</span><strong>${event.company}</strong></div><div><span>Data e horário</span><strong>${event.date}<br>${event.time}</strong></div><div><span>Local</span><strong>${event.location}</strong></div></div></section><section class="info-card"><div class="enrollment"><span class="enrollment-icon">✓</span><div><strong>${isUpcoming ? "Sua inscrição está confirmada" : "Você participou deste evento"}</strong><p>${isUpcoming ? "Sua vaga já está reservada." : "Esta experiência faz parte do seu histórico."}</p></div></div></section>`;

if (event.tournament) {
    document.getElementById("tournamentSection").classList.remove("hidden");
    document.getElementById("rankingStatus").textContent = event.tournament.status;
    document.getElementById("rankingList").innerHTML = event.tournament.rows.map((row, index) => `<article class="ranking-row"><span class="rank ${index < 3 ? "top" : ""}">${index + 1}</span><div class="competitor"><strong>${row.name}</strong><span>${row.detail}</span></div><span class="points">${row.points} <small>pts</small></span></article>`).join("");
}

const profileButton = document.getElementById("profileButton");
const profileMenu = document.getElementById("profileMenu");
profileButton.addEventListener("click", clickEvent => { clickEvent.stopPropagation(); const open = profileMenu.classList.toggle("open"); profileButton.setAttribute("aria-expanded", open); });
document.addEventListener("click", () => { profileMenu.classList.remove("open"); profileButton.setAttribute("aria-expanded", "false"); });
